config/routes.rb
Rails.application.routes.draw do
  resources :payments, only: :create
  resources: gifts

  resources :occasions do
    member do
      get :add_gift_to
      get :remove_gift_from
    end
  end

  resources :recipients

  resources :accounts

  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  belongs_to :user
  has_many :occasions

  validates :street, :suburb, :state, presence: true

  geocoded_by :full_street_address
  after_validation :geocode

  def full_street_address
  	[street, suburb, postcode, state, country].compact.join(', ')
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :set_recipient, only: [:show, :edit, :update, :destroy]

  # GET /recipients
  # GET /recipients.json
  def index
    @recipients = Recipient.all
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
    @occasion = Occasion.new
  end

  # GET /recipients/new
  def new
    @recipient = Recipient.new
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(recipient_params)
    @recipient.user = current_user

    respond_to do |format|
      if @recipient.save
        format.html { redirect_to @recipient, notice: 'Recipient was successfully created.' }
        format.json { render :show, status: :created, location: @recipient }
      else
        format.html { render :new }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipients/1
  # PATCH/PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update(recipient_params)
        format.html { redirect_to @recipient, notice: 'Recipient was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipient }
      else
        format.html { render :edit }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @recipient.destroy
    respond_to do |format|
      format.html { redirect_to recipients_url, notice: 'Recipient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipient
      @recipient = Recipient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipient_params
      params.require(:recipient).permit(:user_id, :first_name, :last_name, :street, :suburb, :postcode, :state, :country, :relationship)
    end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_form.html.erb
<%= simple_form_for(@recipient) do |f| %>
  <%= f.error_notification %>

  	
  	<div class="form-group">
    	<%= f.input :first_name, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :last_name, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :street, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :suburb, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :postcode, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :state, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :country, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :relationship, collection: ['Mother', 'Sister', 'Girlfriend', 'Wife', 'Boyfriend'], input_html: { class: 'form-control' } %>
  	</div>

  <div class="form-group">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/recipients/edit.html.erb
<h1>Editing recipient</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipient %> |
<%= link_to 'Back', recipients_path %>

app/views/recipients/index.html.erb
<h1>Listing recipients</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Street</th>
      <th>Suburb</th>
      <th>Postcode</th>
      <th>State</th>
      <th>Country</th>
      <th>Relationship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipients.each do |recipient| %>
      <tr>
        <td><%= recipient.user %></td>
        <td><%= recipient.first_name %></td>
        <td><%= recipient.last_name %></td>
        <td><%= recipient.street %></td>
        <td><%= recipient.suburb %></td>
        <td><%= recipient.postcode %></td>
        <td><%= recipient.state %></td>
        <td><%= recipient.country %></td>
        <td><%= recipient.relationship %></td>
        <td><%= link_to 'Show', recipient %></td>
        <td><%= link_to 'Edit', edit_recipient_path(recipient) %></td>
        <td><%= link_to 'Destroy', recipient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipient', new_recipient_path %>

app/views/recipients/new.html.erb
<h1>New recipient</h1>

<%= render 'form' %>

<%= link_to 'Back', recipients_path %>

app/views/recipients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @recipient.user %>
</p>

<p>
  <strong>First name:</strong>
  <%= @recipient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @recipient.last_name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @recipient.street %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @recipient.suburb %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @recipient.postcode %>
</p>

<p>
  <strong>State:</strong>
  <%= @recipient.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @recipient.country %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @recipient.relationship %>
</p>
<h3>Add an<%= 'other' if @recipient.occasions.count > 0 %> occasion</h3>
<%= simple_form_for(@occasion) do |f| %>
  <%= f.error_notification %>

    <div class="form-group">
      <%= f.input :recipient_id, as: :hidden, input_html: { class: 'form-control', value: @recipient.id } %>
    </div>
    <div class="form-group">
      <%= f.input :name, input_html: { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.input :occasion_type, input_html: { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.input :message, input_html: { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.input :date, input_html: { class: 'form-control' } %>
    </div>

  <div class="form-group">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

<hr>
<h3>Occasions</h3>
<table>
  <thead>
    <tr>
      <th>Recipient</th>
      <th>Name</th>
      <th>Occasion type</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipient.occasions.each do |occasion| %>
      <tr>
        <td><%= occasion.recipient %></td>
        <td><%= occasion.name %></td>
        <td><%= occasion.occasion_type %></td>
        <td><%= occasion.date %></td>
        <td><%= link_to 'Show', occasion %></td>
        <td><%= link_to 'Edit', edit_occasion_path(occasion) %></td>
        <td><%= link_to 'Destroy', occasion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_recipient_path(@recipient) %> |
<%= link_to 'Back', recipients_path %>