config/routes.rb
Rails.application.routes.draw do
  resources :payments, only: :create
  resources: gifts

  resources :occasions do
    member do
      get :add_gift_to
      get :remove_gift_from
    end
  end

  resources :recipients

  resources :accounts

  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

end

app/models/gift.rb
class Gift < ActiveRecord::Base
	has_many :gift_occasions
	has_many :occasions, through: :gift_occasions
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]
  layout 'home', only: :index

  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(gift_params)

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:name, :description, :price, :image, :slug)
    end
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<%= simple_form_for(@gift) do |f| %>
  <%= f.error_notification %>

  	<div class="form-group">
    	<%= f.input :name, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :description, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :price, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :image, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :slug, input_html: { class: 'form-control' } %>
  	</div>

  <div class="form-group">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/gifts/edit.html.erb
<h1>Editing gift</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
<h1>Listing gifts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Image</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= gift.name %></td>
        <td><%= gift.description %></td>
        <td><%= gift.price %></td>
        <td><%= gift.image %></td>
        <td><%= gift.slug %></td>
        <td><%= link_to 'Show', gift %></td>
        <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
        <td><%= link_to 'Destroy', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift', new_gift_path %>

app/views/gifts/new.html.erb
<h1>New gift</h1>

<%= render 'form' %>

<%= link_to 'Back', gifts_path %>

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gift.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gift.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @gift.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @gift.image %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @gift.slug %>
</p>

<%= link_to 'Edit', edit_gift_path(@gift) %> |
<%= link_to 'Back', gifts_path %>