config/routes.rb
Rails.application.routes.draw do
  resources :payments, only: :create
  resources: gifts

  resources :occasions do
    member do
      get :add_gift_to
      get :remove_gift_from
    end
  end

  resources :recipients

  resources :accounts

  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

end

app/models/occasion.rb
class Occasion < ActiveRecord::Base
  belongs_to :recipient
  has_many :gift_occasions
	has_many :gifts, through: :gift_occasions
end

app/controllers/occasions_controller.rb
class OccasionsController < ApplicationController
  before_action :set_occasion, only: [:remove_gift_from, :add_gift_to, :show, :edit, :update, :destroy]

  def add_gift_to
    @gift = Gift.find(params[:gift])
    @occasion.gifts << @gift
    current_user.account.add_to_balance(@gift.price)
    redirect_to @occasion
  end

  def remove_gift_from
    @occasion.gifts.delete(Gift.find(params[:gift]))
    redirect_to @occasion
  end

  # GET /occasions
  # GET /occasions.json
  def index
    @occasions = Occasion.all
  end

  # GET /occasions/1
  # GET /occasions/1.json
  def show
    @gifts = Gift.all
  end

  # GET /occasions/new
  def new
    @occasion = Occasion.new
  end

  # GET /occasions/1/edit
  def edit
  end

  # POST /occasions
  # POST /occasions.json
  def create
    @occasion = Occasion.new(occasion_params)

    respond_to do |format|
      if @occasion.save
        format.html { redirect_to @occasion, notice: 'Occasion was successfully created.' }
        format.json { render :show, status: :created, location: @occasion }
      else
        format.html { render :new }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occasions/1
  # PATCH/PUT /occasions/1.json
  def update
    respond_to do |format|
      if @occasion.update(occasion_params)
        format.html { redirect_to @occasion, notice: 'Occasion was successfully updated.' }
        format.json { render :show, status: :ok, location: @occasion }
      else
        format.html { render :edit }
        format.json { render json: @occasion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occasions/1
  # DELETE /occasions/1.json
  def destroy
    @occasion.destroy
    respond_to do |format|
      format.html { redirect_to occasions_url, notice: 'Occasion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occasion
      @occasion = Occasion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def occasion_params
      params.require(:occasion).permit(:recipient_id, :name, :occasion_type, :message, :date)
    end
end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/views/occasions/_form.html.erb
<%= simple_form_for(@occasion) do |f| %>
  <%= f.error_notification %>

  	<div class="form-group">
    	<%= f.association :recipient, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :name, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :occasion_type, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :message, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :date, input_html: { class: 'form-control' } %>
  	</div>

  <div class="form-group">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/occasions/edit.html.erb
<h1>Editing occasion</h1>

<%= render 'form' %>

<%= link_to 'Show', @occasion %> |
<%= link_to 'Back', occasions_path %>

app/views/occasions/index.html.erb
<h1>Listing occasions</h1>

<table>
  <thead>
    <tr>
      <th>Recipient</th>
      <th>Name</th>
      <th>Occasion type</th>
      <th>Message</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @occasions.each do |occasion| %>
      <tr>
        <td><%= occasion.recipient %></td>
        <td><%= occasion.name %></td>
        <td><%= occasion.occasion_type %></td>
        <td><%= occasion.message %></td>
        <td><%= occasion.date %></td>
        <td><%= link_to 'Show', occasion %></td>
        <td><%= link_to 'Edit', edit_occasion_path(occasion) %></td>
        <td><%= link_to 'Destroy', occasion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Occasion', new_occasion_path %>

app/views/occasions/new.html.erb
<h1>New occasion</h1>

<%= render 'form' %>

<%= link_to 'Back', occasions_path %>

app/views/occasions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipient:</strong>
  <%= @occasion.recipient %>
</p>

<p>
  <strong>Name:</strong>
  <%= @occasion.name %>
</p>

<p>
  <strong>Occasion type:</strong>
  <%= @occasion.occasion_type %>
</p>

<p>
  <strong>Message:</strong>
  <%= @occasion.message %>
</p>

<p>
  <strong>Date:</strong>
  <%= @occasion.date %>
</p>

<h3>Add gifts</h3>
<% @gifts.each do |gift| %>
  <span class="label label-success">Add <%= link_to gift.name, add_gift_to_occasion_path(gift: gift.id) %></span>
<% end %>

<h3>Gifts added</h3>
<ul>
<% @occasion.gifts.each do |gift| %>
  <li><%= gift.name %> <%= link_to '[remove]', remove_gift_from_occasion_path(gift: gift.id) %></li>
<% end %>
</ul>


<%= link_to 'Edit', edit_occasion_path(@occasion) %> |
<%= link_to 'Back', occasions_path %>