config/routes.rb
Rails.application.routes.draw do
  resources :payments, only: :create
  resources: gifts

  resources :occasions do
    member do
      get :add_gift_to
      get :remove_gift_from
    end
  end

  resources :recipients

  resources :accounts

  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'home#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user

  def add_to_balance(price)
  	update_attribute('balance', balance.to_i + price)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:first_name, :last_name, :picture, :phone, :user_id, :dob)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>

  	<div class="form-group">
    	<%= f.input :first_name, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :last_name, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :picture, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :phone, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.association :user, input_html: { class: 'form-control' } %>
  	</div>
  	<div class="form-group">
    	<%= f.input :dob, input_html: { class: 'form-control' } %>
  	</div>

  <div class="form-group">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Picture</th>
      <th>Phone</th>
      <th>User</th>
      <th>Dob</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.first_name %></td>
        <td><%= account.last_name %></td>
        <td><%= account.picture %></td>
        <td><%= account.phone %></td>
        <td><%= account.user %></td>
        <td><%= account.dob %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-3">
    <div class="panel panel-defaut">
      <div class="panel-body">
        <%= @account.picture %>
        <p><strong><%= @account.first_name %> <%= @account.last_name %></strong></p>
        <strong>Phone:</strong>
          <%= @account.phone_number %>
        <br>
          <strong>Email:</strong>
          <%= @account.user.email %>
        <br>
          <strong>Dob:</strong>
          <%= @account.dob %>
        <br>
        <strong>Balance: </strong><%= number_to_currency(@account.balance) %>
        <br>
        <form action="/payments?amount=<%= @account.balance %>" method="POST" >
          <div style="display:none">
            <input name="utf8" type="hidden" value="&#x2713;" />
            <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
          </div>
          <script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-amount="<%= (@account.balance * 100).to_i %>"
            data-currency="aud" 
            data-name="Autogiftr"
            data-description="Autogiftr balance payment"
            data-email="<%= current_user.email %>">
          </script>
        </form>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-body">
      <%= link_to 'Add Recipient', new_recipient_path, class: 'btn btn-primary' %>
      <hr>
      <table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Relationship</th>
      <th>Occasions</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @account.user.recipients.each do |recipient| %>
      <tr>
        <td><%= recipient.first_name %></td>
        <td><%= recipient.last_name %></td>
        <td><%= recipient.relationship %></td>
        <td>
          <% recipient.occasions.each do |occasion| %>
            <span class="label label-info"><%= link_to occasion.name, occasion %></span>
          <% end %>
        </td>
        <td><%= link_to 'Show', recipient %></td>
        <td><%= link_to 'Edit', edit_recipient_path(recipient) %></td>
        <td><%= link_to 'Destroy', recipient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div style="width:400px;">
  <div id="map" style="width:400px;height:200px;">
  </div>
</div>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>


<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.7.0/underscore-min.js" type="text/javascript"></script>

<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    <% current_user.recipients.each do |recipient| %>
    {
      "lat": <%= recipient.latitude %>,
      "lng": <%= recipient.longitude %>,
      "infowindow": "<%= recipient.first_name %>"
    },
    <% end %>
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>